//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.InfrastructureStatistics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<int> TotalTicketsOpen { get; set; }
        public Nullable<int> TotalResolvedToday { get; set; }
        public Nullable<int> TotalResolvedLastSevenDays { get; set; }
        public Nullable<int> TotalTickets { get; set; }
        public Nullable<int> TotalResolvedLastThirtyDays { get; set; }
        public Nullable<int> TotalNotRespondedToInTwoDays { get; set; }
        public Nullable<decimal> AverageTicketAgeLastSevenDays { get; set; }
        public Nullable<decimal> AverageTicketResolutionTimeLastSevenDays { get; set; }
    }
}
