//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.InfrastructureStatistics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public int Id { get; set; }
        public Nullable<int> CallId { get; set; }
        public string Direction { get; set; }
        public string Status { get; set; }
        public string MissedCallReason { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> AnsweredAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
        public string Duration { get; set; }
        public string AssignedTo { get; set; }
        public string AssignedToEmail { get; set; }
        public string UserName { get; set; }
    }
}
