//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.InfrastructureStatistics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyStatistic
    {
        public int Id { get; set; }
        public Nullable<int> MonthlyTicketCount { get; set; }
        public Nullable<decimal> MonthlyAverageTicketHandlingTime { get; set; }
        public Nullable<int> MonthlyLevelOneResolvedTickets { get; set; }
        public System.DateTime EntryDateTime { get; set; }
    }
}
