//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.InfrastructureStatistics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int OrganisationId { get; set; }
        public string OrganisationName { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<int> TotalOpen { get; set; }
        public Nullable<int> TotalOlderThanSevenDays { get; set; }
        public Nullable<int> TotalOlderThanThirtyDays { get; set; }
    }
}
