//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public Nullable<decimal> TwoDayPercentage { get; set; }
        public Nullable<int> OpenMoreThanSevenDays { get; set; }
        public Nullable<int> OpenMoreThanThirtyDays { get; set; }
        public Nullable<int> TotalPositive { get; set; }
        public Nullable<int> TotalNeutral { get; set; }
        public Nullable<int> TotalNegative { get; set; }
        public Nullable<int> TotalMspMissedCalls { get; set; }
        public Nullable<int> TotalRegisMissedCalls { get; set; }
        public Nullable<System.DateTime> TotalMspHoldTime { get; set; }
        public Nullable<System.DateTime> TotalRegisHoldTime { get; set; }
        public System.DateTime EntryDateTime { get; set; }
    }
}
