//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1Solutions.InfrastructureStatistics.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DueBy { get; set; }
        public string TicketType { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string DepartmentName { get; set; }
        public string AssignedTo { get; set; }
    }
}
